---

- hosts: rear 
  gather_facts: true
  become: yes
  become_method: sudo
  become_user: root
  tasks:
      - name: rear backup
        ansible.builtin.script: /opt/workspace/rear-bkp/rear_backup-ubuntu.sh
          
      - name: copy output.txt
        fetch:
         src: /opt/output.txt
         dest: /opt/workspace/rear-bkp/mails/{{ inventory_hostname }}.txt
         flat: yes

      - name: delete source output.txt
        shell: "rm -rf /opt/output.txt"

- hosts: this 
  gather_facts: true
  become: yes
  become_method: sudo
  become_user: root 
  tasks:
      - name: sending mail
        ansible.builtin.script: /opt/workspace/rear-bkp/a-mail.sh

      - name: del txt files
        shell: "rm -rf /opt/workspace/rear-bkp/mails/*.txt"

# upper 2 lines do same as below 10
#       - name: Ansible delete file glob
#         find:
#          paths: /opt/workspace/rear-bkp/mails 
#          patterns: "*.txt"
#         register: files_to_delete

#       - name: Ansible remove file glob
#         file:
#          path: "{{ item.path }}"
#          state: absent
#         with_items: "{{ files_to_delete.files }}"
