apiVersion: v1
kind: Service
metadata:
  name: ansible-service
  namespace: devops-tools
spec:
  selector:
   app: ansible
  ports:
   - name: ansible-service
     protocol: TCP
     port: 22
     targetPort: 22
     nodePort: 32002
  type: NodePort
