apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-volume
spec:
  storageClassName: nfs
  claimRef:
    name: jenkins-pv-claim
    namespace: devops-tools
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
  claimRef:
    name: jenkins-pv-claim
    namespace: devops-tools
  nfs:
    path: /var/nfsshare/jenkins-data
    server: 192.168.22.14


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: devops-tools
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ansible-pv-volume
spec:
  storageClassName: nfs
  claimRef:
    name: ansible-pv-claim
    namespace: devops-tools
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
  claimRef:
    name: ansible-pv-claim
    namespace: devops-tools
  nfs:
    path: /var/nfsshare/ansible-data
    server: 192.168.22.14

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ansible-pv-claim
  namespace: devops-tools
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
